const data = [
  {
    id: 1,
    title: "ایفون",
    model: 6,
    price: "32,445,852",
    Image: "https://github.com/MohammadrezaNadirkhanloo/Digital-Shop/blob/main/assets/img/11.png",
  },
  {
    id: 2,
    title: "ساعت هوشمند سری",
    model: 7,
    price: "65,424,256",
    Image: "../../assets/img/2.png",
  },
  {
    id: 3,
    title: "ایفون",
    model: 12,
    price: "50,333,654",
    Image: "../../assets/img/my-logo.png",
  },
  {
    id: 4,
    title: "ساعت هوشمند سری",
    model: 11,
    price: "55,846,223",
    Image: "../../assets/img/1.png",
  },
  {
    id: 6,
    title: "ایفون",
    model: 15,
    price: "58,775,564",
    Image: "../../assets/img/11.png",
  },
  {
    id: 7,
    title: "ایفون",
    model: 15,
    price: "58,775,564",
    Image: "../../assets/img/11.png",
  },
  {
    id: 8,
    title: "ساعت هوشمند سری",
    model: 7,
    price: "65,424,256",
    Image: "../../assets/img/1.png",
  },
  {
    id: 9,
    title: "ایفون",
    model: 15,
    price: "58,775,564",
    Image: "../../assets/img/11.png",
  },
  {
    id: 10,
    title: "ساعت هوشمند سری",
    model: 7,
    price: "65,424,256",
    Image: "../../assets/img/1.png",
  },
  {
    id: 11,
    title: "ایفون",
    model: 15,
    price: "58,775,564",
    Image: "../../assets/img/11.png",
  },
  {
    id: 12,
    title: "ایفون",
    model: 15,
    price: "58,775,564",
    Image: "../../assets/img/11.png",
  },
  {
    id: 13,
    title: "ساعت هوشمند سری",
    model: 7,
    price: "65,424,256",
    Image: "../../assets/img/1.png",
  },
  {
    id: 14,
    title: "ساعت هوشمند سری",
    model: 7,
    price: "65,424,256",
    Image: "../../assets/img/1.png",
  },
];

export { data };
